<?php
namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $exercises = [
            'Barbell Bench Press',
            'EZ Bar Bicep Curl',
            'Incline Barbell Bench Press',
            'Dumbbell Curl',
            'Barbell Bicep Curl',
            'Reverse Grip Dumbbell Curl',
            'Standing Hammer Curl',
            'Standing Barbell Drag Curl',
            'Dumbbell Bench Press',
            'Incline Dumbbell Bench Press',
            'Seated Incline Bicep Curl',
            'Decline Dumbbell Bench Press',
            'Concentration Curl',
            'Seated Hammer Curl',
            'Twisting Dumbbell Curl',
            'Incline Hammer Curl',
            'Reverse grip EZ bar curl',
            'Prone Dumbbell Spider Curl',
            'Press Up',
            'Diamond Press Up',
            'Clap Press Up',
            'Single Arm Medicine Ball Press Up',
            'Close Grip Press Up',
            'Spiderman Press Up',
            'Decline Bench Press',
            'Floor Dumbbell Press',
            'Dumbbell Fly',
            'Incline Dumbbell Fly',
            'Cable Tricep Push Down',
            'Dips',
            'Dumbbell Skullcrushers',
            'Barbell Skullcrushers',
            'Overhead Barbell Tricep Extension',
            'Overhead Dumbbell Tricep Extension',
            'Dumbbell Kick Back',
            'Cable Overhead Tricep Extension',
            'Pull Ups',
            'Chin Ups',
            'Lat Pulldown',
            'Straight Arm Pull Down',
            'Barbell Row',
            'Dumbbell Row',
            'Seated Cable Row',
            'Inverted Row',
            'Inverted Underhand Row',
            'Single Arm Dumbbell Row',
            'Dumbbell Pullover',
            'Barbell Pullover',
            'Underhand Lateral Pulldown',
            'Face Pulls',
            'Seated Bent Over Delt Fly',
            'Lying Rear Delt Fly',
            'Dumbbell Incline Rear Delt Fly',
            'One Arm Cable Crossover',
            'Single Arm Cable Chest Press',
            'Military Press',
            'Dumbbell Military Press',
            'Lateral Side Raises',
            'Seated Dumbbell Shoulder Press',
            'Upright Dumbbell Rows',
            'Upright Cable Rows',
            'Dumbbell Lunge',
            'Barbell Lunge',
            'Barbell Squats',
            'Dumbbell Squats',
            'Barbell Deadlift',
            'Dumbbell Stiff Legged Deadlift',
            'Stiff Legged Deadlift',
            'One Legged Dumbbell Deadlift',
            'Step Ups',
            'Dumbbell Step Ups',
            'Barbell Step Ups',
            'Barbell Bulgarian Split Squat',
            'Dumbbell Bulgarian Split Squat',
            'Dumbbell Goblet Squat',
            'Sit Up',
            'Crunch',
            'Weighted Crunch',
            'Overhead Plate Sit Up',
            'Side Crunch',
            'Reverse Crunch',
            'Lying Leg Raise',
            'Hanging Twisting Leg Raise',
            'Hanging Leg Raise',
            'Russian Plate Twists',
            'V Sit Up',
            'Ab Roller',
            'Cable Wood Chop',
            'Cable Core Rotation',
            'Cable Crunch',
            'Bicycle Crunches',
            'Close Grip Bench Press',
            'Side Jackknife',
            'Single Leg Glute Bridge',
            'Glute Bridge',
            'Barbell Glute Bridge',
            'Squat',
            'Box Squat',
            'Dumbbell Box Squat',
            'Burpees',
            'Jump Squat',
            'Mountain Climbers',
            'Renegade Row',
            'Dumbbell Clean',
            'Barbell Clean and Press',
            'Dumbbell Clean and Press',
            'Barbell Shrug',
            'Dumbbell Shrug',
            'Jog',
            'Jump Rope',
            'Jumping Jacks',
            'Kick Through',
            'Barbell Front Squat to Shoulder Press',
            'Jump Lunge',
            'Jumping Jack Dumbbell Press',
            'Hanging Chin Up',
            'Assisted Pull Up',
            'Negative Pull Up',
            'Boxing',
            'T Press Up',
            'Band T Press Up',
            'Dumbbell T Press Up',
            'Band T Plank',
            'Dumbbell T Plank',
            'T Plank',
            'Seated Ab Crunch',
            'Seated Side Raises',
            'Band Press Up',
            'Bench Dips',
            'Decline Press Up',
            'Russian Twist',
            'Rotating Side Plank',
            'Spider Crawl',
            'Running',
            'Wall Walk',
            'Side Lunge',
            'Dumbbell Side Lunge',
            'Barbell Side Lung '
        ];


        foreach ($exercises as $ex) {
            $ex = Exercise::create([
                'name' => $ex,
                'slug' => Str::slug($ex),
                'description' => 'description of exercise'
            ]);
        }
    }
}
